# -*- coding: utf-8 -*-
"""Aula3sub.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1waaX99nRlUXUduJC0z7_75wDmpVoMNk-
"""

# ETE PORTO DIGITAL
# DISCIPLINA: LPC1
# PROFESSOR: CLOVES
# ESTUDANTE: TARCÍSIO FRANKLIN PEREIRA

print('Olá, ETE PORTO DIGITAL!')